#!/bin/bash

function compile() {
    LIB=../../lib
    first=${1:-.}
    shift
    files=
    for i in $first "$@"; do
	for f in ${i%%/}/*.java; do
	    files="${files} $f"
	done
    done
    echo $files
    javac -cp .:$LIB/lwjgl-2.8.4/res:$LIB/lwjgl-2.8.4/jar/lwjgl.jar:$LIB/lwjgl-2.8.4/jar/lwjgl_test.jar:$LIB/lwjgl-2.8.4/jar/lwjgl_util.jar:$LIB/lwjgl-2.8.4/jar/jinput.jar:$LIB/slick-util/slick-util.jar:$LIB/slick/slick.jar: $files 2>&1 | sed -e '1 s/.*/\o033[0;36m&\o033[0m/; /\^/ { n; s/.*/\o033[0;36m&\o033[0m/; }'
}

function run() {
    local toRun
    toRun=$1
    if [ -z "$toRun" ]; then
	echo "Usage: $(basename $0) package.ClassName"
	echo "  Runs package.ClassName (if you are located in Engine/)"
	exit 1
    fi
    
    if ! [ -d lib -a -d src -a -d res ]; then
	echo "You're in the wrong directory, move to Engine/"
	exit 2
    fi
    
    LIB=lib
    java -cp src/:$LIB/lwjgl-2.8.4/jar/lwjgl.jar:$LIB/lwjgl-2.8.4/jar/lwjgl_util.jar:$LIB/lwjgl-2.8.4/jar/jinput.jar:$LIB/slick-util/slick-util.jar:$LIB/slick/slick.jar: -Djava.library.path=$LIB/lwjgl-2.8.4/native/linux/ $toRun
}

function install() {
    if [ -d scripts ]; then
	echo "Changed path"
	export PATH=$PATH:$PWD/scripts/
    else
	echo "Wrong directory, move to the root directory (root/scripts/../)"
	exit 1
    fi
}    

function usage() {
    echo "Usage: $(basename $0) [command] [args]"
    echo "Commands:"
    sed "$0" -ne 's/^[ \t]*do\([a-z-]\{1,\}[ \t]*\)).*/   \1/p'
}

function edittsa() {
    editcode "$0"
}

function editcode() {
    local file dir curfile
    file="$1"
    if [ -f "$file" ]; then
        emacsclient --no-wait "$file"
    else
	curfile=$(find src/ -name $file.java)
	if [ -n "$curfile" ]; then
	    editcode $curfile
	fi
	if [ -n "${file//[^.]/}" ]; then
	    editcode "src/${file//\.//}.java"
	fi
    fi
}

function create-jar() {
    if [ ! -d jar ]; then
	echo "Move to Engine/"
    fi
    tsa compile-default && \
	(cd jar; ./create-windows.sh) && \
	java -jar jar/jarsplice-0.40-CLI.jar -fat jar/fat-windows.jar -jars lib/lwjgl-2.8.4/jar/jinput.jar\;lib/lwjgl-2.8.4/jar/lwjgl.jar\;lib/lwjgl-2.8.4/jar/lwjgl_util.jar\;lib/slick/slick.jar\;jar/windows.jar -nats lib/lwjgl-2.8.4/native/windows/jinput-dx8_64.dll\;lib/lwjgl-2.8.4/native/windows/jinput-dx8.dll\;lib/lwjgl-2.8.4/native/windows/jinput-raw_64.dll\;lib/lwjgl-2.8.4/native/windows/jinput-raw.dll\;lib/lwjgl-2.8.4/native/windows/lwjgl64.dll\;lib/lwjgl-2.8.4/native/windows/lwjgl.dll\;lib/lwjgl-2.8.4/native/windows/OpenAL32.dll\;lib/lwjgl-2.8.4/native/windows/OpenAL64.dll -main splash.SplashScreen && \
	cp jar/fat-windows.jar /mnt/usb/
}

function compile-default() {
    if [ ! -d src/ ]; then
	echo "Move to Engine/"
	exit 1
    fi
    cd src/event
    compile ../{event,character,sound,splash,levels}
}

function run-default() {
    run event.EventTest
}

function status() {
    git status | grep -v class
}

function getchanges() {
    git status -s | sed -ne '/\.class/ !{ s/ M \(.*\)/\1/p; }'
}

# Prints out what it's doing
function GIT() {
    echo "git $@"
    git "$@"
}

function addchanged() {
    local list
    list=$1
    if [ "$list" = -l ]; then
	getchanges
    else
	set -x
	getchanges | xargs -I{} git add {}
	set +x
    fi
}

function main() {
    what="$1"
    shift

    case do$what in
	docompile) compile "$@";;
	doinstall) install "$@";;
	dorun) run "$@";;
	doem) editcode "$@";;
	doedittsa) edittsa "$@";;
	docompile-default) compile-default "$@";;
	dojar) create-jar "$@";;
	dorun-default) run-default "$@";;
	dostatus) status "$@";;
	dochanges) addchanged "$@";;
	do-h|do--help|do) usage "$@";;
	do*) editcode "$what";;
    esac
}

main "$@"
